# How each question answer nudges each mood score.
# Keys must match Question.key values in the DB.
# Values are dicts of {mood_label: weight} and can be negative.

# ---------------------------------------------------------------------------
# Category importance multipliers  (applied in inference.py)
# ---------------------------------------------------------------------------
CATEGORY_WEIGHTS = {
    "emotion":    1.60,   # Strongest mood signal
    "energy":     1.30,   # Maps directly to energy/valence
    "cognition":  1.10,   # Sharp vs scattered matters
    "activity":   1.00,   # Moderate signal
    "preference": 0.90,   # Influences track selection more than mood
    "context":    0.70,   # Weakest mood signal
}

# ---------------------------------------------------------------------------
# Cross-question synergy bonuses
# Each entry: (set of rawValue answers that must ALL be present, mood, bonus)
# ---------------------------------------------------------------------------
SYNERGY_BONUSES = [
    ({"sad", "drifting", "escape"},           "melancholic",  0.35),
    ({"happy", "charged", "party"},           "celebratory",  0.40),
    ({"calm", "relaxing", "sleep"},           "calm",         0.35),
    ({"sharp", "motivated", "focus"},         "focused",      0.30),
    ({"tense", "scattered", "working"},       "anxious",      0.25),
    ({"excited", "social", "party"},          "celebratory",  0.35),
    ({"drained", "sad", "relaxing"},          "melancholic",  0.30),
    ({"charged", "exercising", "uplift"},     "energized",    0.35),
    ({"calm", "drifting", "relax"},           "calm",         0.30),
    ({"happy", "exercising", "uplift"},       "energized",    0.30),
    ({"flat", "blank", "escape"},             "melancholic",  0.30),
    ({"sharp", "working", "focus"},           "focused",      0.28),
    ({"excited", "charged", "uplift"},        "energized",    0.32),
    ({"calm", "sleeping", "sleep"},           "calm",         0.40),
    ({"tense", "drained", "escape"},          "anxious",      0.25),
    ({"happy", "social", "lyrics"},           "celebratory",  0.25),
    ({"sad", "alone", "lyrics"},              "melancholic",  0.28),
    ({"motivated", "exercising", "party"},    "energized",    0.30),
]

QUESTION_DEFINITIONS = [
    {
        "key": "energy_level",
        "text": "How much energy do you have right now?",
        "category": "energy",
        "inputType": "select",
        "order": 1,
        "options": [
            {"rawValue": "drained", "label": "Completely drained"},
            {"rawValue": "low", "label": "Low, running on empty"},
            {"rawValue": "mid", "label": "Somewhere in the middle"},
            {"rawValue": "good", "label": "Pretty good"},
            {"rawValue": "charged", "label": "Fully charged"},
        ],
    },
    {
        "key": "emotional_tone",
        "text": "Which of these best describes how you're feeling?",
        "category": "emotion",
        "inputType": "select",
        "order": 2,
        "options": [
            {"rawValue": "happy", "label": "Happy & light"},
            {"rawValue": "calm", "label": "Calm & peaceful"},
            {"rawValue": "sad", "label": "Low or sad"},
            {"rawValue": "tense", "label": "Tense or restless"},
            {"rawValue": "flat", "label": "Numb or flat"},
            {"rawValue": "excited", "label": "Excited"},
        ],
    },
    {
        "key": "mental_state",
        "text": "Where is your head at right now?",
        "category": "cognition",
        "inputType": "select",
        "order": 3,
        "options": [
            {"rawValue": "sharp", "label": "Sharp, ready to focus"},
            {"rawValue": "scattered", "label": "Scattered, hard to concentrate"},
            {"rawValue": "drifting", "label": "Drifting, lost in thought"},
            {"rawValue": "motivated", "label": "Switched on, motivated"},
            {"rawValue": "blank", "label": "Blank, not thinking much"},
        ],
    },
    {
        "key": "activity",
        "text": "What are you about to do or currently doing?",
        "category": "activity",
        "inputType": "select",
        "order": 4,
        "options": [
            {"rawValue": "working", "label": "Working or studying"},
            {"rawValue": "exercising", "label": "Exercising or moving"},
            {"rawValue": "relaxing", "label": "Relaxing or winding down"},
            {"rawValue": "commuting", "label": "Commuting or travelling"},
            {"rawValue": "social", "label": "Socialising or celebrating"},
            {"rawValue": "sleeping", "label": "Trying to sleep or rest"},
        ],
    },
    {
        "key": "social_setting",
        "text": "Who are you listening with?",
        "category": "context",
        "inputType": "select",
        "order": 5,
        "options": [
            {"rawValue": "alone", "label": "Just me"},
            {"rawValue": "others", "label": "With others around"},
            {"rawValue": "kids", "label": "With kids"},
            {"rawValue": "meeting", "label": "In a meeting / working space"},
        ],
    },
    {
        "key": "music_preference",
        "text": "What kind of sound feels right at this moment?",
        "category": "preference",
        "inputType": "select",
        "order": 6,
        "options": [
            {"rawValue": "lyrics", "label": "I want lyrics, something to connect with"},
            {"rawValue": "no_lyrics", "label": "No words, just music"},
            {"rawValue": "background", "label": "Background sound, barely there"},
            {"rawValue": "surprise", "label": "Surprise me"},
        ],
    },
    {
        "key": "music_language",
        "text": "Which language or music culture do you want right now?",
        "category": "preference",
        "inputType": "select",
        "order": 7,
        "options": [
            {"rawValue": "no_preference", "label": "No preference"},
            {"rawValue": "hindi", "label": "Hindi / Bollywood"},
            {"rawValue": "english", "label": "English / Hollywood"},
            {"rawValue": "marathi", "label": "Marathi"},
            {"rawValue": "punjabi", "label": "Punjabi"},
            {"rawValue": "instrumental", "label": "Instrumental only"},
        ],
    },
    {
        "key": "music_style",
        "text": "What style should the playlist lean toward?",
        "category": "preference",
        "inputType": "select",
        "order": 8,
        "options": [
            {"rawValue": "no_preference", "label": "No preference"},
            {"rawValue": "bollywood", "label": "Bollywood"},
            {"rawValue": "hollywood", "label": "Hollywood / English pop"},
            {"rawValue": "pop", "label": "Pop"},
            {"rawValue": "indie", "label": "Indie"},
            {"rawValue": "classical", "label": "Indian classical"},
            {"rawValue": "raga", "label": "Classical raga"},
            {"rawValue": "lofi", "label": "Lo-fi"},
            {"rawValue": "devotional", "label": "Devotional"},
        ],
    },
    {
        "key": "playlist_goal",
        "text": "What should this playlist help you do?",
        "category": "preference",
        "inputType": "select",
        "order": 9,
        "options": [
            {"rawValue": "focus", "label": "Focus and concentrate"},
            {"rawValue": "relax", "label": "Relax and slow down"},
            {"rawValue": "uplift", "label": "Lift my mood"},
            {"rawValue": "escape", "label": "Get lost in the music"},
            {"rawValue": "party", "label": "Bring energy and vibe"},
            {"rawValue": "sleep", "label": "Rest or fall asleep"},
        ],
    },
    {
        "key": "preferred_artist",
        "text": "Any artist you want to hear? Leave blank if not.",
        "category": "preference",
        "inputType": "text",
        "order": 10,
        "options": [],
    },
    {
        "key": "time_of_day",
        "text": "What time of day is it for you?",
        "category": "context",
        "inputType": "select",
        "order": 11,
        "options": [
            {"rawValue": "morning", "label": "Morning — fresh start"},
            {"rawValue": "afternoon", "label": "Afternoon — mid-day groove"},
            {"rawValue": "evening", "label": "Evening — winding down"},
            {"rawValue": "late_night", "label": "Late night — quiet hours"},
        ],
    },
    {
        "key": "nostalgia_craving",
        "text": "What are you in the mood for?",
        "category": "preference",
        "inputType": "select",
        "order": 12,
        "options": [
            {"rawValue": "discover_new", "label": "Discover something new"},
            {"rawValue": "old_favorites", "label": "Old favourites, comfort songs"},
            {"rawValue": "mix_both", "label": "A mix of both"},
        ],
    },
]

# ---------------------------------------------------------------------------
# QUESTION_WEIGHTS — mood nudges per (question_key + rawValue) combo
# ---------------------------------------------------------------------------
QUESTION_WEIGHTS = {
    # ── energy_level ──────────────────────────────────────────────────────
    "energy_level_drained": {
        "calm": 0.45,
        "melancholic": 0.55,
        "anxious": 0.15,
        "focused": -0.20,
        "energized": -0.50,
        "celebratory": -0.45,
    },
    "energy_level_low": {
        "calm": 0.30,
        "melancholic": 0.35,
        "anxious": 0.10,
        "focused": -0.10,
        "energized": -0.30,
        "celebratory": -0.25,
    },
    "energy_level_mid": {
        "focused": 0.35,
        "calm": 0.15,
        "melancholic": 0.05,
        "anxious": 0.00,
        "energized": 0.05,
        "celebratory": 0.00,
    },
    "energy_level_good": {
        "energized": 0.35,
        "focused": 0.25,
        "celebratory": 0.15,
        "calm": -0.10,
        "melancholic": -0.15,
        "anxious": 0.05,
    },
    "energy_level_charged": {
        "energized": 0.55,
        "celebratory": 0.35,
        "focused": 0.15,
        "calm": -0.25,
        "melancholic": -0.30,
        "anxious": 0.10,
    },
    # ── emotional_tone ────────────────────────────────────────────────────
    "emotional_tone_happy": {
        "energized": 0.35,
        "celebratory": 0.40,
        "melancholic": -0.40,
        "anxious": -0.20,
        "calm": 0.10,
        "focused": 0.05,
    },
    "emotional_tone_calm": {
        "calm": 0.55,
        "focused": 0.25,
        "melancholic": 0.10,
        "energized": -0.30,
        "celebratory": -0.35,
        "anxious": -0.30,
    },
    "emotional_tone_sad": {
        "melancholic": 0.60,
        "calm": 0.15,
        "anxious": 0.15,
        "focused": -0.15,
        "energized": -0.45,
        "celebratory": -0.50,
    },
    "emotional_tone_tense": {
        "anxious": 0.65,
        "melancholic": 0.10,
        "energized": 0.10,
        "calm": -0.40,
        "focused": -0.20,
        "celebratory": -0.35,
    },
    "emotional_tone_flat": {
        "melancholic": 0.45,
        "calm": 0.35,
        "focused": -0.10,
        "energized": -0.40,
        "celebratory": -0.45,
        "anxious": 0.10,
    },
    "emotional_tone_excited": {
        "celebratory": 0.55,
        "energized": 0.35,
        "focused": -0.10,
        "calm": -0.35,
        "melancholic": -0.45,
        "anxious": -0.15,
    },
    # ── mental_state ──────────────────────────────────────────────────────
    "mental_state_sharp": {
        "focused": 0.60,
        "energized": 0.15,
        "calm": 0.10,
        "anxious": -0.25,
        "melancholic": -0.20,
        "celebratory": 0.05,
    },
    "mental_state_scattered": {
        "anxious": 0.55,
        "melancholic": 0.15,
        "focused": -0.35,
        "calm": -0.25,
        "energized": 0.05,
        "celebratory": -0.20,
    },
    "mental_state_drifting": {
        "melancholic": 0.40,
        "calm": 0.35,
        "focused": -0.20,
        "energized": -0.30,
        "celebratory": -0.35,
        "anxious": 0.05,
    },
    "mental_state_motivated": {
        "energized": 0.45,
        "celebratory": 0.30,
        "focused": 0.15,
        "melancholic": -0.40,
        "calm": -0.25,
        "anxious": -0.10,
    },
    "mental_state_blank": {
        "calm": 0.45,
        "melancholic": 0.30,
        "focused": -0.15,
        "energized": -0.35,
        "celebratory": -0.40,
        "anxious": 0.05,
    },
    # ── activity ──────────────────────────────────────────────────────────
    "activity_working": {
        "focused": 0.60,
        "calm": 0.15,
        "anxious": 0.10,
        "energized": -0.15,
        "celebratory": -0.35,
        "melancholic": 0.00,
    },
    "activity_exercising": {
        "energized": 0.60,
        "celebratory": 0.20,
        "focused": 0.10,
        "calm": -0.30,
        "melancholic": -0.35,
        "anxious": -0.10,
    },
    "activity_relaxing": {
        "calm": 0.55,
        "melancholic": 0.20,
        "focused": -0.15,
        "energized": -0.40,
        "celebratory": -0.30,
        "anxious": -0.20,
    },
    "activity_commuting": {
        "focused": 0.35,
        "calm": 0.25,
        "energized": 0.15,
        "melancholic": 0.15,
        "anxious": 0.05,
        "celebratory": -0.10,
    },
    "activity_social": {
        "celebratory": 0.55,
        "energized": 0.30,
        "focused": -0.25,
        "calm": -0.15,
        "melancholic": -0.35,
        "anxious": -0.10,
    },
    "activity_sleeping": {
        "calm": 0.65,
        "melancholic": 0.15,
        "focused": -0.20,
        "energized": -0.50,
        "celebratory": -0.55,
        "anxious": -0.30,
    },
    # ── social_setting ────────────────────────────────────────────────────
    "social_setting_alone": {
        "focused": 0.10,
        "melancholic": 0.10,
        "calm": 0.05,
        "celebratory": -0.05,
        "energized": 0.00,
        "anxious": 0.00,
    },
    "social_setting_others": {
        "celebratory": 0.20,
        "energized": 0.10,
        "focused": -0.10,
        "melancholic": -0.15,
        "calm": -0.05,
        "anxious": 0.00,
    },
    "social_setting_kids": {
        "calm": 0.20,
        "celebratory": 0.10,
        "anxious": -0.10,
        "melancholic": -0.10,
        "focused": -0.05,
        "energized": 0.05,
    },
    "social_setting_meeting": {
        "focused": 0.30,
        "calm": 0.15,
        "anxious": 0.10,
        "celebratory": -0.20,
        "energized": -0.10,
        "melancholic": -0.05,
    },
    # ── music_preference ──────────────────────────────────────────────────
    "music_preference_lyrics": {
        "celebratory": 0.10,
        "energized": 0.10,
        "melancholic": 0.05,
        "calm": -0.05,
        "focused": -0.10,
        "anxious": -0.05,
    },
    "music_preference_no_lyrics": {
        "focused": 0.15,
        "calm": 0.10,
        "anxious": -0.05,
        "energized": -0.05,
        "celebratory": -0.10,
        "melancholic": 0.05,
    },
    "music_preference_background": {
        "calm": 0.20,
        "focused": 0.10,
        "anxious": -0.10,
        "energized": -0.15,
        "celebratory": -0.20,
        "melancholic": 0.10,
    },
    "music_preference_surprise": {
        "energized": 0.05,
        "celebratory": 0.05,
        "calm": 0.00,
        "focused": 0.00,
        "melancholic": 0.00,
        "anxious": 0.00,
    },
    # ── music_language (NEW — previously missing) ─────────────────────────
    "music_language_no_preference": {
        "energized": 0.00,
        "celebratory": 0.00,
        "focused": 0.00,
        "calm": 0.00,
        "melancholic": 0.00,
        "anxious": 0.00,
    },
    "music_language_hindi": {
        "celebratory": 0.12,
        "energized": 0.10,
        "melancholic": 0.05,
        "calm": -0.05,
        "focused": -0.05,
        "anxious": -0.03,
    },
    "music_language_english": {
        "energized": 0.08,
        "celebratory": 0.06,
        "focused": 0.04,
        "calm": -0.02,
        "melancholic": -0.02,
        "anxious": -0.02,
    },
    "music_language_marathi": {
        "calm": 0.10,
        "melancholic": 0.08,
        "celebratory": 0.05,
        "energized": 0.00,
        "focused": -0.02,
        "anxious": -0.03,
    },
    "music_language_punjabi": {
        "energized": 0.15,
        "celebratory": 0.18,
        "focused": -0.05,
        "calm": -0.08,
        "melancholic": -0.10,
        "anxious": -0.05,
    },
    "music_language_instrumental": {
        "focused": 0.18,
        "calm": 0.15,
        "melancholic": 0.05,
        "energized": -0.08,
        "celebratory": -0.12,
        "anxious": -0.05,
    },
    # ── music_style (NEW — previously missing) ────────────────────────────
    "music_style_no_preference": {
        "energized": 0.00,
        "celebratory": 0.00,
        "focused": 0.00,
        "calm": 0.00,
        "melancholic": 0.00,
        "anxious": 0.00,
    },
    "music_style_bollywood": {
        "celebratory": 0.14,
        "energized": 0.12,
        "melancholic": 0.05,
        "calm": -0.05,
        "focused": -0.08,
        "anxious": -0.05,
    },
    "music_style_hollywood": {
        "energized": 0.10,
        "celebratory": 0.08,
        "focused": 0.04,
        "calm": -0.03,
        "melancholic": -0.03,
        "anxious": -0.03,
    },
    "music_style_pop": {
        "energized": 0.12,
        "celebratory": 0.10,
        "focused": -0.05,
        "calm": -0.08,
        "melancholic": -0.05,
        "anxious": -0.05,
    },
    "music_style_indie": {
        "melancholic": 0.12,
        "calm": 0.10,
        "focused": 0.05,
        "energized": -0.05,
        "celebratory": -0.08,
        "anxious": 0.00,
    },
    "music_style_classical": {
        "calm": 0.18,
        "focused": 0.14,
        "melancholic": 0.08,
        "energized": -0.10,
        "celebratory": -0.12,
        "anxious": -0.10,
    },
    "music_style_raga": {
        "calm": 0.20,
        "focused": 0.12,
        "melancholic": 0.10,
        "energized": -0.12,
        "celebratory": -0.14,
        "anxious": -0.08,
    },
    "music_style_lofi": {
        "calm": 0.20,
        "focused": 0.15,
        "melancholic": 0.10,
        "energized": -0.15,
        "celebratory": -0.18,
        "anxious": -0.08,
    },
    "music_style_devotional": {
        "calm": 0.25,
        "melancholic": 0.08,
        "focused": 0.05,
        "energized": -0.12,
        "celebratory": -0.10,
        "anxious": -0.15,
    },
    # ── playlist_goal ─────────────────────────────────────────────────────
    "playlist_goal_focus": {
        "focused": 0.95,
        "calm": 0.15,
        "energized": 0.05,
        "anxious": -0.25,
        "melancholic": -0.10,
        "celebratory": -0.25,
    },
    "playlist_goal_relax": {
        "calm": 0.95,
        "melancholic": 0.20,
        "focused": 0.05,
        "energized": -0.35,
        "celebratory": -0.35,
        "anxious": -0.30,
    },
    "playlist_goal_uplift": {
        "energized": 0.60,
        "celebratory": 0.55,
        "calm": 0.05,
        "focused": 0.10,
        "melancholic": -0.40,
        "anxious": -0.15,
    },
    "playlist_goal_escape": {
        "melancholic": 0.55,
        "calm": 0.40,
        "focused": -0.05,
        "energized": -0.20,
        "celebratory": -0.20,
        "anxious": -0.05,
    },
    "playlist_goal_party": {
        "celebratory": 0.90,
        "energized": 0.60,
        "focused": -0.20,
        "calm": -0.35,
        "melancholic": -0.50,
        "anxious": -0.10,
    },
    "playlist_goal_sleep": {
        "calm": 1.00,
        "melancholic": 0.25,
        "focused": -0.20,
        "energized": -0.60,
        "celebratory": -0.60,
        "anxious": -0.35,
    },
    # ── time_of_day (NEW question) ────────────────────────────────────────
    "time_of_day_morning": {
        "energized": 0.25,
        "focused": 0.20,
        "celebratory": 0.05,
        "calm": -0.05,
        "melancholic": -0.15,
        "anxious": -0.08,
    },
    "time_of_day_afternoon": {
        "focused": 0.15,
        "energized": 0.10,
        "calm": 0.05,
        "celebratory": 0.00,
        "melancholic": -0.05,
        "anxious": 0.00,
    },
    "time_of_day_evening": {
        "calm": 0.20,
        "melancholic": 0.12,
        "focused": -0.05,
        "energized": -0.10,
        "celebratory": 0.05,
        "anxious": -0.05,
    },
    "time_of_day_late_night": {
        "calm": 0.30,
        "melancholic": 0.22,
        "focused": -0.10,
        "energized": -0.25,
        "celebratory": -0.20,
        "anxious": 0.05,
    },
    # ── nostalgia_craving (NEW question) ──────────────────────────────────
    "nostalgia_craving_discover_new": {
        "energized": 0.12,
        "celebratory": 0.08,
        "focused": 0.05,
        "calm": -0.05,
        "melancholic": -0.08,
        "anxious": -0.02,
    },
    "nostalgia_craving_old_favorites": {
        "melancholic": 0.18,
        "calm": 0.12,
        "celebratory": 0.05,
        "focused": -0.05,
        "energized": -0.08,
        "anxious": -0.05,
    },
    "nostalgia_craving_mix_both": {
        "energized": 0.02,
        "celebratory": 0.02,
        "focused": 0.02,
        "calm": 0.02,
        "melancholic": 0.02,
        "anxious": 0.00,
    },
}

# ---------------------------------------------------------------------------
# Per-option intensity values  (graduated, no longer flat 1.0)
# ---------------------------------------------------------------------------
OPTION_WEIGHTS = {
    # energy_level — reflects how much intensity the answer carries
    "drained":    0.15,
    "low":        0.35,
    "mid":        0.55,
    "good":       0.80,
    "charged":    1.00,
    # emotional_tone
    "happy":      1.00,
    "calm":       0.75,
    "sad":        0.30,
    "tense":      0.55,
    "flat":       0.20,
    "excited":    1.00,
    # mental_state
    "sharp":      1.00,
    "scattered":  0.30,
    "drifting":   0.40,
    "motivated":  1.00,
    "blank":      0.20,
    # activity — all equally intentional, keep at 1.0
    "working":    1.00,
    "exercising": 1.00,
    "relaxing":   1.00,
    "commuting":  1.00,
    "social":     1.00,
    "sleeping":   1.00,
    # social_setting — all equally valid contexts
    "alone":      1.00,
    "others":     1.00,
    "kids":       1.00,
    "meeting":    1.00,
    # music_preference
    "lyrics":         1.00,
    "no_lyrics":      1.00,
    "background":     1.00,
    "surprise":       1.00,
    # music_language
    "no_preference":  1.00,
    "hindi":          1.00,
    "english":        1.00,
    "marathi":        1.00,
    "punjabi":        1.00,
    "instrumental":   1.00,
    # music_style
    "bollywood":      1.00,
    "hollywood":      1.00,
    "pop":            1.00,
    "indie":          1.00,
    "classical":      1.00,
    "raga":           1.00,
    "lofi":           1.00,
    "devotional":     1.00,
    # playlist_goal — all equally intentional
    "focus":          1.00,
    "relax":          1.00,
    "uplift":         1.00,
    "escape":         1.00,
    "party":          1.00,
    "sleep":          1.00,
    # time_of_day (new)
    "morning":        1.00,
    "afternoon":      1.00,
    "evening":        1.00,
    "late_night":     1.00,
    # nostalgia_craving (new)
    "discover_new":   1.00,
    "old_favorites":  1.00,
    "mix_both":       1.00,
}

MUSIC_PREFERENCE_OVERRIDES = {
    "lyrics": {"song": 0.80, "instrumental": 0.15, "ambient": 0.05},
    "no_lyrics": {"song": 0.05, "instrumental": 0.75, "ambient": 0.20},
    "background": {"song": 0.05, "instrumental": 0.25, "ambient": 0.70},
    "surprise": None,
}
