# How each question answer nudges each mood score.
# Keys must match Question.key values in the DB.
# Values are dicts of {mood_label: weight} and can be negative.

QUESTION_DEFINITIONS = [
    {
        "key": "energy_level",
        "text": "How much energy do you have right now?",
        "category": "energy",
        "inputType": "select",
        "order": 1,
        "options": [
            {"rawValue": "drained", "label": "Completely drained"},
            {"rawValue": "low", "label": "Low, running on empty"},
            {"rawValue": "mid", "label": "Somewhere in the middle"},
            {"rawValue": "good", "label": "Pretty good"},
            {"rawValue": "charged", "label": "Fully charged"},
        ],
    },
    {
        "key": "emotional_tone",
        "text": "Which of these best describes how you're feeling?",
        "category": "emotion",
        "inputType": "select",
        "order": 2,
        "options": [
            {"rawValue": "happy", "label": "Happy & light"},
            {"rawValue": "calm", "label": "Calm & peaceful"},
            {"rawValue": "sad", "label": "Low or sad"},
            {"rawValue": "tense", "label": "Tense or restless"},
            {"rawValue": "flat", "label": "Numb or flat"},
            {"rawValue": "excited", "label": "Excited"},
        ],
    },
    {
        "key": "mental_state",
        "text": "Where is your head at right now?",
        "category": "cognition",
        "inputType": "select",
        "order": 3,
        "options": [
            {"rawValue": "sharp", "label": "Sharp, ready to focus"},
            {"rawValue": "scattered", "label": "Scattered, hard to concentrate"},
            {"rawValue": "drifting", "label": "Drifting, lost in thought"},
            {"rawValue": "motivated", "label": "Switched on, motivated"},
            {"rawValue": "blank", "label": "Blank, not thinking much"},
        ],
    },
    {
        "key": "activity",
        "text": "What are you about to do or currently doing?",
        "category": "activity",
        "inputType": "select",
        "order": 4,
        "options": [
            {"rawValue": "working", "label": "Working or studying"},
            {"rawValue": "exercising", "label": "Exercising or moving"},
            {"rawValue": "relaxing", "label": "Relaxing or winding down"},
            {"rawValue": "commuting", "label": "Commuting or travelling"},
            {"rawValue": "social", "label": "Socialising or celebrating"},
            {"rawValue": "sleeping", "label": "Trying to sleep or rest"},
        ],
    },
    {
        "key": "social_setting",
        "text": "Who are you listening with?",
        "category": "context",
        "inputType": "select",
        "order": 5,
        "options": [
            {"rawValue": "alone", "label": "Just me"},
            {"rawValue": "others", "label": "With others around"},
            {"rawValue": "kids", "label": "With kids"},
            {"rawValue": "meeting", "label": "In a meeting / working space"},
        ],
    },
    {
        "key": "music_preference",
        "text": "What kind of sound feels right at this moment?",
        "category": "preference",
        "inputType": "select",
        "order": 6,
        "options": [
            {"rawValue": "lyrics", "label": "I want lyrics, something to connect with"},
            {"rawValue": "no_lyrics", "label": "No words, just music"},
            {"rawValue": "background", "label": "Background sound, barely there"},
            {"rawValue": "surprise", "label": "Surprise me"},
        ],
    },
    {
        "key": "music_language",
        "text": "Which language or music culture do you want right now?",
        "category": "preference",
        "inputType": "select",
        "order": 7,
        "options": [
            {"rawValue": "no_preference", "label": "No preference"},
            {"rawValue": "hindi", "label": "Hindi / Bollywood"},
            {"rawValue": "english", "label": "English / Hollywood"},
            {"rawValue": "marathi", "label": "Marathi"},
            {"rawValue": "punjabi", "label": "Punjabi"},
            {"rawValue": "instrumental", "label": "Instrumental only"},
        ],
    },
    {
        "key": "music_style",
        "text": "What style should the playlist lean toward?",
        "category": "preference",
        "inputType": "select",
        "order": 8,
        "options": [
            {"rawValue": "no_preference", "label": "No preference"},
            {"rawValue": "bollywood", "label": "Bollywood"},
            {"rawValue": "hollywood", "label": "Hollywood / English pop"},
            {"rawValue": "pop", "label": "Pop"},
            {"rawValue": "indie", "label": "Indie"},
            {"rawValue": "classical", "label": "Indian classical"},
            {"rawValue": "raga", "label": "Classical raga"},
            {"rawValue": "lofi", "label": "Lo-fi"},
            {"rawValue": "devotional", "label": "Devotional"},
        ],
    },
    {
        "key": "playlist_goal",
        "text": "What should this playlist help you do?",
        "category": "preference",
        "inputType": "select",
        "order": 9,
        "options": [
            {"rawValue": "focus", "label": "Focus and concentrate"},
            {"rawValue": "relax", "label": "Relax and slow down"},
            {"rawValue": "uplift", "label": "Lift my mood"},
            {"rawValue": "escape", "label": "Get lost in the music"},
            {"rawValue": "party", "label": "Bring energy and vibe"},
            {"rawValue": "sleep", "label": "Rest or fall asleep"},
        ],
    },
    {
        "key": "preferred_artist",
        "text": "Any artist you want to hear? Leave blank if not.",
        "category": "preference",
        "inputType": "text",
        "order": 10,
        "options": [],
    },
]

QUESTION_WEIGHTS = {
    "energy_level_drained": {
        "calm": 0.45,
        "melancholic": 0.55,
        "anxious": 0.15,
        "focused": -0.20,
        "energized": -0.50,
        "celebratory": -0.45,
    },
    "energy_level_low": {
        "calm": 0.30,
        "melancholic": 0.35,
        "anxious": 0.10,
        "focused": -0.10,
        "energized": -0.30,
        "celebratory": -0.25,
    },
    "energy_level_mid": {
        "focused": 0.35,
        "calm": 0.15,
        "melancholic": 0.05,
        "anxious": 0.00,
        "energized": 0.05,
        "celebratory": 0.00,
    },
    "energy_level_good": {
        "energized": 0.35,
        "focused": 0.25,
        "celebratory": 0.15,
        "calm": -0.10,
        "melancholic": -0.15,
        "anxious": 0.05,
    },
    "energy_level_charged": {
        "energized": 0.55,
        "celebratory": 0.35,
        "focused": 0.15,
        "calm": -0.25,
        "melancholic": -0.30,
        "anxious": 0.10,
    },
    "emotional_tone_happy": {
        "energized": 0.35,
        "celebratory": 0.40,
        "melancholic": -0.40,
        "anxious": -0.20,
        "calm": 0.10,
        "focused": 0.05,
    },
    "emotional_tone_calm": {
        "calm": 0.55,
        "focused": 0.25,
        "melancholic": 0.10,
        "energized": -0.30,
        "celebratory": -0.35,
        "anxious": -0.30,
    },
    "emotional_tone_sad": {
        "melancholic": 0.60,
        "calm": 0.15,
        "anxious": 0.15,
        "focused": -0.15,
        "energized": -0.45,
        "celebratory": -0.50,
    },
    "emotional_tone_tense": {
        "anxious": 0.65,
        "melancholic": 0.10,
        "energized": 0.10,
        "calm": -0.40,
        "focused": -0.20,
        "celebratory": -0.35,
    },
    "emotional_tone_flat": {
        "melancholic": 0.45,
        "calm": 0.35,
        "focused": -0.10,
        "energized": -0.40,
        "celebratory": -0.45,
        "anxious": 0.10,
    },
    "emotional_tone_excited": {
        "celebratory": 0.55,
        "energized": 0.35,
        "focused": -0.10,
        "calm": -0.35,
        "melancholic": -0.45,
        "anxious": -0.15,
    },
    "mental_state_sharp": {
        "focused": 0.60,
        "energized": 0.15,
        "calm": 0.10,
        "anxious": -0.25,
        "melancholic": -0.20,
        "celebratory": 0.05,
    },
    "mental_state_scattered": {
        "anxious": 0.55,
        "melancholic": 0.15,
        "focused": -0.35,
        "calm": -0.25,
        "energized": 0.05,
        "celebratory": -0.20,
    },
    "mental_state_drifting": {
        "melancholic": 0.40,
        "calm": 0.35,
        "focused": -0.20,
        "energized": -0.30,
        "celebratory": -0.35,
        "anxious": 0.05,
    },
    "mental_state_motivated": {
        "energized": 0.45,
        "celebratory": 0.30,
        "focused": 0.15,
        "melancholic": -0.40,
        "calm": -0.25,
        "anxious": -0.10,
    },
    "mental_state_blank": {
        "calm": 0.45,
        "melancholic": 0.30,
        "focused": -0.15,
        "energized": -0.35,
        "celebratory": -0.40,
        "anxious": 0.05,
    },
    "activity_working": {
        "focused": 0.60,
        "calm": 0.15,
        "anxious": 0.10,
        "energized": -0.15,
        "celebratory": -0.35,
        "melancholic": 0.00,
    },
    "activity_exercising": {
        "energized": 0.60,
        "celebratory": 0.20,
        "focused": 0.10,
        "calm": -0.30,
        "melancholic": -0.35,
        "anxious": -0.10,
    },
    "activity_relaxing": {
        "calm": 0.55,
        "melancholic": 0.20,
        "focused": -0.15,
        "energized": -0.40,
        "celebratory": -0.30,
        "anxious": -0.20,
    },
    "activity_commuting": {
        "focused": 0.35,
        "calm": 0.25,
        "energized": 0.15,
        "melancholic": 0.15,
        "anxious": 0.05,
        "celebratory": -0.10,
    },
    "activity_social": {
        "celebratory": 0.55,
        "energized": 0.30,
        "focused": -0.25,
        "calm": -0.15,
        "melancholic": -0.35,
        "anxious": -0.10,
    },
    "activity_sleeping": {
        "calm": 0.65,
        "melancholic": 0.15,
        "focused": -0.20,
        "energized": -0.50,
        "celebratory": -0.55,
        "anxious": -0.30,
    },
    "social_setting_alone": {
        "focused": 0.10,
        "melancholic": 0.10,
        "calm": 0.05,
        "celebratory": -0.05,
        "energized": 0.00,
        "anxious": 0.00,
    },
    "social_setting_others": {
        "celebratory": 0.20,
        "energized": 0.10,
        "focused": -0.10,
        "melancholic": -0.15,
        "calm": -0.05,
        "anxious": 0.00,
    },
    "social_setting_kids": {
        "calm": 0.20,
        "celebratory": 0.10,
        "anxious": -0.10,
        "melancholic": -0.10,
        "focused": -0.05,
        "energized": 0.05,
    },
    "social_setting_meeting": {
        "focused": 0.30,
        "calm": 0.15,
        "anxious": 0.10,
        "celebratory": -0.20,
        "energized": -0.10,
        "melancholic": -0.05,
    },
    "music_preference_lyrics": {
        "celebratory": 0.10,
        "energized": 0.10,
        "melancholic": 0.05,
        "calm": -0.05,
        "focused": -0.10,
        "anxious": -0.05,
    },
    "music_preference_no_lyrics": {
        "focused": 0.15,
        "calm": 0.10,
        "anxious": -0.05,
        "energized": -0.05,
        "celebratory": -0.10,
        "melancholic": 0.05,
    },
    "music_preference_background": {
        "calm": 0.20,
        "focused": 0.10,
        "anxious": -0.10,
        "energized": -0.15,
        "celebratory": -0.20,
        "melancholic": 0.10,
    },
    "music_preference_surprise": {
        "energized": 0.05,
        "celebratory": 0.05,
        "calm": 0.00,
        "focused": 0.00,
        "melancholic": 0.00,
        "anxious": 0.00,
    },
    "playlist_goal_focus": {
        "focused": 0.95,
        "calm": 0.15,
        "energized": 0.05,
        "anxious": -0.25,
        "melancholic": -0.10,
        "celebratory": -0.25,
    },
    "playlist_goal_relax": {
        "calm": 0.95,
        "melancholic": 0.20,
        "focused": 0.05,
        "energized": -0.35,
        "celebratory": -0.35,
        "anxious": -0.30,
    },
    "playlist_goal_uplift": {
        "energized": 0.60,
        "celebratory": 0.55,
        "calm": 0.05,
        "focused": 0.10,
        "melancholic": -0.40,
        "anxious": -0.15,
    },
    "playlist_goal_escape": {
        "melancholic": 0.55,
        "calm": 0.40,
        "focused": -0.05,
        "energized": -0.20,
        "celebratory": -0.20,
        "anxious": -0.05,
    },
    "playlist_goal_party": {
        "celebratory": 0.90,
        "energized": 0.60,
        "focused": -0.20,
        "calm": -0.35,
        "melancholic": -0.50,
        "anxious": -0.10,
    },
    "playlist_goal_sleep": {
        "calm": 1.00,
        "melancholic": 0.25,
        "focused": -0.20,
        "energized": -0.60,
        "celebratory": -0.60,
        "anxious": -0.35,
    },
}

OPTION_WEIGHTS = {
    "drained": 1.0,
    "low": 1.0,
    "mid": 1.0,
    "good": 1.0,
    "charged": 1.0,
    "happy": 1.0,
    "calm": 0.75,
    "sad": 0.25,
    "tense": 0.50,
    "flat": 0.20,
    "excited": 1.0,
    "sharp": 1.0,
    "scattered": 0.30,
    "drifting": 0.40,
    "motivated": 1.0,
    "blank": 0.20,
    "working": 1.0,
    "exercising": 1.0,
    "relaxing": 1.0,
    "commuting": 1.0,
    "social": 1.0,
    "sleeping": 1.0,
    "alone": 1.0,
    "others": 1.0,
    "kids": 1.0,
    "meeting": 1.0,
    "lyrics": 1.0,
    "no_lyrics": 1.0,
    "background": 1.0,
    "surprise": 1.0,
    "no_preference": 1.0,
    "hindi": 1.0,
    "english": 1.0,
    "marathi": 1.0,
    "punjabi": 1.0,
    "instrumental": 1.0,
    "bollywood": 1.0,
    "hollywood": 1.0,
    "pop": 1.0,
    "indie": 1.0,
    "classical": 1.0,
    "raga": 1.0,
    "lofi": 1.0,
    "devotional": 1.0,
    "focus": 1.0,
    "relax": 1.0,
    "uplift": 1.0,
    "escape": 1.0,
    "party": 1.0,
    "sleep": 1.0,
}

MUSIC_PREFERENCE_OVERRIDES = {
    "lyrics": {"song": 0.80, "instrumental": 0.15, "ambient": 0.05},
    "no_lyrics": {"song": 0.05, "instrumental": 0.75, "ambient": 0.20},
    "background": {"song": 0.05, "instrumental": 0.25, "ambient": 0.70},
    "surprise": None,
}
